-- =============================================
-- DATABASE: city_hub (The Command Center)
-- =============================================
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgres_fdw;

-- 1. CENTRAL MAP TABLE
-- 1. CENTRAL MAP TABLE
CREATE TABLE inspections_hub (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- LINK TO GEO REF (Where?)
    address_id UUID NOT NULL, -- Links to city_geo_ref.adresses(id)
    -- Note: We no longer store 'adresse_civique' text here. It is fetched from the address_id.
    
    -- LINK TO CODES (What?)
    usage_code_id UUID NOT NULL, -- Links to city_codes.usages(id)
    conformity_snapshot_id UUID, -- Links to city_codes.conformity_snapshots(id)
    
    status_conformite TEXT CHECK (status_conformite IN ('Conforme', 'Non-conforme')),
    date_inspection DATE NOT NULL,
    
    -- Link to Foreign Database (The "Spoke")
    source_db TEXT NOT NULL, -- e.g. 'city_industrie'
    source_id UUID NOT NULL,  -- ID in the foreign DB
    
    created_at TIMESTAMP DEFAULT NOW()
);
-- Spatial Index is now on the ADDRESS in city_geo_ref, but we might cache it here for speed?
-- For now, we rely on the Join to city_geo_ref for the Geometry. 
-- OR, we keep a cached copy of the Point for fast map rendering without Joins?
-- Let's keep `geom` as a CACHED column for performance, trigger-updated.
ALTER TABLE inspections_hub ADD COLUMN geom GEOMETRY(POINT, 4326);
CREATE INDEX idx_hub_geom ON inspections_hub USING GIST (geom);

-- 2. AUDIT LOG (Internal)
CREATE TABLE security_audit_log (
    id SERIAL PRIMARY KEY,
    user_name TEXT,
    action_type TEXT,
    target_record TEXT,
    timestamp TIMESTAMP DEFAULT NOW()
);

-- 3. USERS & SECURITY
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT CHECK (role IN ('admin', 'inspector')) DEFAULT 'inspector',
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP DEFAULT NOW()
);

-- Initial Admin (Password: admin123)
-- Hash generated via bcrypt (cost 10) for 'admin123'
INSERT INTO users (username, password_hash, role)
VALUES ('admin', '$2a$10$X.x.x.x.x.x.x.x.x.x.x', 'admin'); 
-- NOTE: Real hash needs to be generated by the app later or manually. 
-- For safety, we will insert the user via the app's seed script instead of SQL to ensure valid bcrypt.
